title: VIFF Schedule Maker
description: A user manual for using the VIFF Schedule Maker
theme: just-the-docs

url: https://RZhangBCIT.github.io/VIFF

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
